// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0161:Convert to file-scoped namespace", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "namespace", Target = "~N:Microsoft.FellowOakDicom.Serialization")]
[assembly: SuppressMessage("Style", "IDE0073:The file header is missing or not located at the top of the file", Justification = "<Pending>")]
[assembly: SuppressMessage("Style", "IDE0005:Using directive is unnecessary.", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.")]
[assembly: SuppressMessage("Compiler", "CS1573:Using directive is unnecessary.", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomArrayJsonConverter.Write(System.Text.Json.Utf8JsonWriter,FellowOakDicom.DicomDataset[],System.Text.Json.JsonSerializerOptions)")]
[assembly: SuppressMessage("Style", "IDE0008:Use explicit type", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomArrayJsonConverter.Write(System.Text.Json.Utf8JsonWriter,FellowOakDicom.DicomDataset[],System.Text.Json.JsonSerializerOptions)")]
[assembly: SuppressMessage("Style", "IDE0036:Order modifiers", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "type", Target = "~T:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~F:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter._jsonTextEncodings")]
[assembly: SuppressMessage("Performance", "CA1802:Use literals where appropriate", Justification = "<Pending>", Scope = "member", Target = "~F:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter._personNameComponentGroupDelimiter")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~F:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter._personNameComponentGroupDelimiter")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~F:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter._personNameComponentGroupNames")]
[assembly: SuppressMessage("Documentation", "CA1200:Avoid using cref tags with a prefix", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter.CreateBulkDataUriByteBuffer(System.String)~FellowOakDicom.IO.Buffer.IBulkDataUriByteBuffer")]
[assembly: SuppressMessage("Design", "CA1054:URI-like parameters should not be strings", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter.CreateBulkDataUriByteBuffer(System.String)~FellowOakDicom.IO.Buffer.IBulkDataUriByteBuffer")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter.FindValue(System.Text.Json.Utf8JsonReader,System.String,System.String)~System.String")]
[assembly: SuppressMessage("Documentation", "CA1200:Avoid using cref tags with a prefix", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter.Write(System.Text.Json.Utf8JsonWriter,FellowOakDicom.DicomDataset,System.Text.Json.JsonSerializerOptions)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter.Write(System.Text.Json.Utf8JsonWriter,FellowOakDicom.DicomDataset,System.Text.Json.JsonSerializerOptions)")]
[assembly: SuppressMessage("Documentation", "CA1200:Avoid using cref tags with a prefix", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter.Read(System.Text.Json.Utf8JsonReader@,System.Type,System.Text.Json.JsonSerializerOptions)~FellowOakDicom.DicomDataset")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter.ReadJsonPersonName(System.Text.Json.Utf8JsonReader@)~System.String[]")]
[assembly: SuppressMessage("Style", "IDE0008:Use explicit type", Justification = "The project is copied from fo-dicom, will be removed once fo-dicom has no release.", Scope = "member", Target = "~M:Microsoft.FellowOakDicom.Serialization.DicomJsonConverter.ReadJsonBulkDataUri(System.Text.Json.Utf8JsonReader@)~FellowOakDicom.IO.Buffer.IBulkDataUriByteBuffer")]
