//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Health.Dicom.SqlServer.Features.Schema.Model
{
    using Microsoft.Health.SqlServer.Features.Client;
    using Microsoft.Health.SqlServer.Features.Schema.Model;

    internal class AddCustomTagsInputTableTypeV1TableValuedParameterDefinition : TableValuedParameterDefinition<AddCustomTagsInputTableTypeV1Row>
    {
        internal AddCustomTagsInputTableTypeV1TableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.AddCustomTagsInputTableType_1")
        {
        }

        internal readonly VarCharColumn TagPath = new VarCharColumn("TagPath", 64);
        internal readonly VarCharColumn TagVR = new VarCharColumn("TagVR", 2);
        internal readonly TinyIntColumn TagLevel = new TinyIntColumn("TagLevel");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { TagPath, TagVR, TagLevel };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, AddCustomTagsInputTableTypeV1Row rowData)
        {
            TagPath.Set(record, 0, rowData.TagPath);
            TagVR.Set(record, 1, rowData.TagVR);
            TagLevel.Set(record, 2, rowData.TagLevel);
        }
    }

    internal struct AddCustomTagsInputTableTypeV1Row
    {
        internal AddCustomTagsInputTableTypeV1Row(System.String TagPath, System.String TagVR, System.Byte TagLevel)
        {
            this.TagPath = TagPath;
            this.TagVR = TagVR;
            this.TagLevel = TagLevel;
        }

        internal System.String TagPath { get; }
        internal System.String TagVR { get; }
        internal System.Byte TagLevel { get; }
    }

    internal class InsertStringCustomTagTableTypeV1TableValuedParameterDefinition : TableValuedParameterDefinition<InsertStringCustomTagTableTypeV1Row>
    {
        internal InsertStringCustomTagTableTypeV1TableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.InsertStringCustomTagTableType_1")
        {
        }

        internal readonly BigIntColumn TagKey = new BigIntColumn("TagKey");
        internal readonly TinyIntColumn TagLevel = new TinyIntColumn("TagLevel");
        internal readonly NVarCharColumn StringValue = new NVarCharColumn("StringValue", 64);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { TagKey, TagLevel, StringValue };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, InsertStringCustomTagTableTypeV1Row rowData)
        {
            TagKey.Set(record, 0, rowData.TagKey);
            TagLevel.Set(record, 1, rowData.TagLevel);
            StringValue.Set(record, 2, rowData.StringValue);
        }
    }

    internal struct InsertStringCustomTagTableTypeV1Row
    {
        internal InsertStringCustomTagTableTypeV1Row(System.Int64 TagKey, System.Byte TagLevel, System.String StringValue)
        {
            this.TagKey = TagKey;
            this.TagLevel = TagLevel;
            this.StringValue = StringValue;
        }

        internal System.Int64 TagKey { get; }
        internal System.Byte TagLevel { get; }
        internal System.String StringValue { get; }
    }
}