//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Health.Dicom.SqlServer.Features.Schema.Model
{
    using Microsoft.Health.SqlServer.Features.Client;
    using Microsoft.Health.SqlServer.Features.Schema.Model;

    internal class AddCustomTagsInputTableTypeV1TableValuedParameterDefinition : TableValuedParameterDefinition<AddCustomTagsInputTableTypeV1Row>
    {
        internal AddCustomTagsInputTableTypeV1TableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.AddCustomTagsInputTableType_1")
        {
        }

        internal readonly VarCharColumn Path = new VarCharColumn("Path", 64);
        internal readonly VarCharColumn VR = new VarCharColumn("VR", 2);
        internal readonly TinyIntColumn Level = new TinyIntColumn("Level");
        internal readonly TinyIntColumn Status = new TinyIntColumn("Status");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { Path, VR, Level, Status };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, AddCustomTagsInputTableTypeV1Row rowData)
        {
            Path.Set(record, 0, rowData.Path);
            VR.Set(record, 1, rowData.VR);
            Level.Set(record, 2, rowData.Level);
            Status.Set(record, 3, rowData.Status);
        }
    }

    internal struct AddCustomTagsInputTableTypeV1Row
    {
        internal AddCustomTagsInputTableTypeV1Row(System.String Path, System.String VR, System.Byte Level, System.Byte Status)
        {
            this.Path = Path;
            this.VR = VR;
            this.Level = Level;
            this.Status = Status;
        }

        internal System.String Path { get; }
        internal System.String VR { get; }
        internal System.Byte Level { get; }
        internal System.Byte Status { get; }
    }
}